version: '3.8'

services:
  db:
    image: postgres
    container_name: marginwatch-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marginwatch
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: marginwatch-backend
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    tty: true
    ports:
      - "5000:5000"
    environment:
      - MW_ENV=prod

  frontend:
    build:
      context: ./frontend
    container_name: marginwatch-frontend
    restart: always
    ports:
      - "3000:3000"  # Optional for testing from host
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  nginx:
    image: nginx
    container_name: marginwatch-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./frontend/out:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  pgdata:
