version: '3.8'

services:
  db:
    image: postgres
    container_name: marginwatch-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: marginwatch
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: marginwatch-app
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    tty: true
